version: '3'
services:
  blind_pwn:
    build: ./task
      #    restart: always
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "300M"

