version: '3'
services:
  http_server:
    build: ./task
    container_name: http_server
    restart: always
    ports:
      - 1337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "150M"

